#include "hal/gpio.h"
#include "config.h"
#include "hal/gpio_config.h"
#include "stm32f10x.h"

static bool g_gpio_initialized = false;

void gpio_init(void) {
	if (g_gpio_initialized) {
		return;
	}
	GPIOA->CRL &=
	    ~(GPIO_CRL_MODE0 | GPIO_CRL_CNF0 | GPIO_CRL_MODE1 | GPIO_CRL_CNF1);
	GPIOA->CRL |= (GPIO_CNF_INPUT_PULL << 0) | (GPIO_CNF_INPUT_PULL << 4);

	GPIOA->ODR &= ~(BIT_MASK(0) | BIT_MASK(1) | BIT_MASK(8) | BIT_MASK(11) |
	                BIT_MASK(12) | BIT_MASK(13) | BIT_MASK(14) | BIT_MASK(15));

	GPIOA->CRL &= ~(GPIO_CRL_MODE4 | GPIO_CRL_CNF4);
	GPIOA->CRL |= (GPIO_MODE_OUTPUT_2MHZ << 16) | (GPIO_CNF_OUTPUT_PP << 18);
	GPIOA->ODR |= BIT_MASK(SPI_CS_PIN);

	GPIOA->CRL &= ~(GPIO_CRL_MODE5 | GPIO_CRL_CNF5);
	GPIOA->CRL |= (GPIO_MODE_OUTPUT_2MHZ << 20) | (GPIO_CNF_AF_PP << 22);

	GPIOA->CRL &= ~(GPIO_CRL_MODE6 | GPIO_CRL_CNF6);
	GPIOA->CRL |= (GPIO_CNF_INPUT_FLOAT << 26);

	GPIOA->CRL &= ~(GPIO_CRL_MODE7 | GPIO_CRL_CNF7);
	GPIOA->CRL |= (GPIO_MODE_OUTPUT_2MHZ << 28) | (GPIO_CNF_AF_PP << 30);

	GPIOA->CRH |= (GPIO_CNF_INPUT_PULL << 4) | (GPIO_CNF_INPUT_PULL << 8);

	GPIOA->CRL &= ~(GPIO_CRL_MODE2 | GPIO_CRL_CNF2);
	GPIOA->CRL |= (GPIO_MODE_OUTPUT_2MHZ << 8) | (GPIO_CNF_AF_PP << 10);

	GPIOA->CRL &= ~(GPIO_CRL_MODE3 | GPIO_CRL_CNF3);
	GPIOA->CRL |= (GPIO_CNF_INPUT_FLOAT << 12);

	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN;
	GPIOB->CRL = GPIOB_CRL_PULLDOWN_CFG;
	GPIOB->CRH = GPIOB_CRH_PULLDOWN_CFG;
	GPIOB->ODR = 0x0000U;

	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;
	GPIOC->CRL = GPIOC_CRL_PULLDOWN_CFG;
	GPIOC->CRH = GPIOC_CRH_PULLDOWN_CFG;
	GPIOC->ODR = 0x0000U;

	g_gpio_initialized = true;
}

void gpio_deinit(void) {
	RCC->APB2ENR &=
	    ~(RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPBEN | RCC_APB2ENR_IOPCEN);
}
